const deadlines = [
    {
        studentid: 1,
        proffid: 2,
        marks: 10,
        description: 'Solve this problem and make sure to submit it on time',
        googleDriveLink: 'https://drive.google.com/your_link_here',
        timeStamp: '2023-09-19T14:30:00',
        timeStampDeadline: '2023-09-20T14:30:00',
        projectname:'CyberSecurity',
    },
    {
        studentid: 1,
        proffid: 2,
        marks: 10,
        description: 'Submit the text file which explains the folder structure of the project',
        googleDriveLink: 'https://drive.google.com/your_link_here',
        timeStamp: '2023-09-20T14:30:00',
        timeStampDeadline: '2023-09-21T14:30:00',
        projectname:'CyberSecurity',
    },
    {
        studentid: 2,
        proffid: 3,
        marks: 15,
        description: 'Complete the research paper',
        googleDriveLink: 'https://drive.google.com/another_link_here',
        timeStamp: '2023-09-20T10:00:00',
        projectname:'MemoryForensics',
    },
    {
        studentid: 3,
        proffid: 1,
        marks: 12,
        description: 'Create a presentation noce',
        googleDriveLink: 'https://drive.google.com/yet_another_link_here',
        timeStamp: '2023-09-21T16:45:00',
        projectname:'proccessForensics',
    },
];
export default deadlines;